---

- name: provision Debian web server with WordPress
  vars:
    timezone: 'Europe/Moscow'
  remote_user: "{{ user }}"
  hosts: all
  become: yes
  roles:
    - role: essentials
      tags: essentials

    - role: iptables
      tags: iptables

    - role: nginx
      tags: nginx

    - role: mysql
      tags: mysql

    - role: php
      tags: php

    - role: wordpress
      vars:
        wordpress_domain: 'example.app.dev'
        mysql_database:   "{{ mysql_credentials[0].database }}"
        mysql_user:       "{{ mysql_credentials[0].username }}"
        mysql_password:   "{{ mysql_credentials[0].password }}"
      tags: wordpress
      when: mysql_credentials is defined

    - role: wordpress
      vars:
        wordpress_domain: 'site1.app.dev'
        mysql_database:   "{{ mysql_credentials[1].database }}"
        mysql_user:       "{{ mysql_credentials[1].username }}"
        mysql_password:   "{{ mysql_credentials[1].password }}"
      tags: wordpress
      when: mysql_credentials is defined

    - role: wordpress
      vars:
        wordpress_domain: 'site2.app.dev'
        mysql_database:   "{{ mysql_credentials[2].database }}"
        mysql_user:       "{{ mysql_credentials[2].username }}"
        mysql_password:   "{{ mysql_credentials[2].password }}"
      tags: wordpress
      when: mysql_credentials is defined
