---

- name: provision debian web server
  vars:
    timezone: 'Europe/Moscow'
    ruby_version: 2.2.2
  remote_user: "{{ user }}"
  hosts: all
  become: yes
  roles:
    - role: essentials
      tags: essentials

    - role: iptables
      tags: iptables

    - role: mysql
      tags: mysql

    - role: php
      tags: php

    - role: nodejs
      tags: nodejs

    - role: rvm
      tags: rvm

    - role: nginx
      tags: nginx

    - role: wordpress
      vars:
        wordpress_domain: 'example.com'
        mysql_database: "{{ mysql_credentials[0].database }}"
        mysql_user:     "{{ mysql_credentials[0].username }}"
        mysql_password: "{{ mysql_credentials[0].password }}"
      tags: wordpress
      when: mysql_credentials is defined

    - role: redis
      tags: redis

    - role: postgresql
      tags: postgresql

    - role: exim
      tags: exim
      yandex_login: "{{ email }}"
      yandex_password: "{{ lookup('env', 'YANDEX_PASSWORD') }}"

    - role: redmine
      tags: redmine

    - role: openvpn
      tags: openvpn

    - role: tor
      tags: tor

    - role: haproxy
      tags: haproxy

    - role: deploy
      tags:
        - deploy
        - kanban
      app_name: kanban
      git_repo: https://github.com/somlor/kanban
      git_branch: master
      shared_dirs:
        - tmp
        - log
      shared_files:
        - .env
      force: no

  tasks:
    - name: env variables are set
      lineinfile:
        dest: "/home/{{ user }}/.bash_profile"
        line: "{{ item }}"
        create: yes
      with_items:
        - "ENV=production"
        - "RAILS_ENV=production"
