---

- name: provision debian web server
  vars:
    timezone: 'Europe/Moscow'
    ruby_version: 2.2.2
  remote_user: "{{ user }}"
  hosts: all
  become: yes
  roles:
    - role: essentials
      tags: essentials

    - role: iptables
      tags: iptables

    - role: mysql
      tags: mysql
      vars:
        mysql_database: 'database_name'
        mysql_user: 'user_name'
        mysql_password: 'user_password'

    - role: php
      tags: php

    - role: nodejs
      tags: nodejs

    - role: rvm
      tags: rvm

    - role: ssl
      tags: ssl

    - role: nginx
      tags: nginx

    - role: wordpress
      vars:
        wordpress_domain: 'example.com'
      tags: wordpress

    - role: redis
      tags: redis

    - role: postgresql
      tags: postgresql

    - role: exim
      tags: exim
      yandex_login: "{{ email }}"
      yandex_password: "{{ lookup('env', 'YANDEX_PASSWORD') }}"

    - role: redmine
      tags: redmine

    - role: openvpn
      tags: openvpn

    - role: tor
      tags: tor

    - role: haproxy
      tags: haproxy

    - role: deploy
      tags:
        - deploy
        - kanban
      app_name: kanban
      git_repo: https://github.com/somlor/kanban
      git_branch: master
      shared_dirs:
        - tmp
        - log
      shared_files:
        - .env
      force: no
