---
- set_fact: www_directory="/var/www/{{ wordpress_domain }}/www"
- set_fact: wordpress_username="{{ wordpress_domain | truncate(32, False, '') | regex_replace('[\.\-]+', '_') }}"

- include: wordpress-default.yml
  when: use_301_redirect is not defined or use_301_redirect == false

- include: wordpress-301-redirect.yml
  when: use_301_redirect is defined and use_301_redirect == true

- include: backup.yml
  when: create_backups is defined and create_backups == true
