---

- name: add dotdeb.org's GPG key
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present

# If this repository is not available you must choose another one from https://www.dotdeb.org/mirrors/
- name: add dotdeb.org's mirror repository
  apt_repository:
    repo: "deb http://dotdeb.thefox.com.fr jessie all"
    state: present
    update_cache: yes

- name: add dotdeb.org's mirror sources repository
  apt_repository:
    repo: "deb-src http://dotdeb.thefox.com.fr jessie all"
    state: present
    update_cache: yes

- name: PHP 7 is installed
  apt: name={{ item }} state=present
  with_items:
   - php7.0-cli
   - php7.0-curl
   - php7.0-dev
   - php7.0-zip
   - php7.0-bz2
   - php7.0-fpm
   - php7.0-gd
   - php7.0-xml
   - php7.0-mysql
   - php7.0-mcrypt
   - php7.0-mbstring
   - php7.0-opcache

- name: change php-fpm settings
  lineinfile:
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    state: present
    line: "{{ item.key }} = {{ item.value }}"
    regexp: "^(.*){{ item.key }}"
  with_items:
    - { key: 'pm.max_children', value: 10 }
    - { key: 'pm.max_requests', value: 200 }
  notify:
    - restart php-fpm

- name: change php.ini settings
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    state: present
    line: "{{ item.key }} = {{ item.value }}"
    regexp: "^(.*){{ item.key }}"
  with_items:
    - { key: 'date.timezone', value: "{{ timezone }}" }
    - { key: 'upload_max_filesize', value: '8M' }
    - { key: 'max_execution_time', value: 60 }
    - { key: 'max_input_vars', value: 5000 }
    - { key: 'cgi.fix_pathinfo', value: 0 }
  notify:
    - restart php-fpm

- name: change fastcgi_params in nginx
  lineinfile:
    dest: /etc/nginx/fastcgi_params
    state: present
    line: "{{ item.key }} {{ item.value }};"
    regexp: "^(.*){{ item.key }}"
  with_items:
    - { key: 'fastcgi_pass',                 value: "unix:/var/run/php/$php_fpm_socket.socket" }
    - { key: 'fastcgi_index',                value: "index.php" }
    - { key: 'fastcgi_param',                value: "SCRIPT_FILENAME $root_path$fastcgi_script_name" }
    - { key: 'fastcgi_intercept_errors',     value: "on" }
    - { key: 'fastcgi_connect_timeout',      value: "600s" }
    - { key: 'fastcgi_send_timeout',         value: "600s" }
    - { key: 'fastcgi_read_timeout',         value: "600s" }
    - { key: 'fastcgi_buffer_size',          value: "128k" }
    - { key: 'fastcgi_buffers',              value: "8 256k" }
    - { key: 'fastcgi_busy_buffers_size',    value: "256k" }
    - { key: 'fastcgi_temp_file_write_size', value: "256k" }
  notify:
    - restart php-fpm
    - restart nginx
